// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdjdwysfkjqgfdidcmnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkamR3eXNma2pxZ2ZkaWRjbW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODg1NDQsImV4cCI6MjA3MjA2NDU0NH0.NxQ3helblErIqK_g2LwDKXp6Wr_NOb4c2MHpILxMP6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});